.github/workflows/build.yml, flake.lock, flake.nix, update-versions.py, versions.json
@oscar-izval to build `1.6.6`, upgrade `nixpkgs-unstable` was required; however, doing so forces rebuild of most packages; thus, I decided to change the way we build packages to allow incremental builds, as rebuilding everything in a single shot is more prone to error and leaves less room to cache individual packages, as if any package fails, the ones that were successfully built will not be pushed to Cachix.
=> feat: Add Terraform `1.6.6`

.github/workflows/publish.yml
A missing field is currently causing an issue in the FlakeHub publishing pipeline:
=> ci: Fix FlakeHub release pipeline

update-versions.py, versions.json
=> Improve update-versions.py

.github/workflows/build.yml, flake.nix
=> fix: Build packages by cycle / Push builds to Cachix

flake.nix
The word `all` appears twice in the names of the cycle packages:
```
this derivation will be built:
/nix/store/vqn18gq4sd0v24v48rxv16nhyw4dv6rp-terraform-all-all-1.6.drv
```
=> fix: Drop duplicated `all` from cycle packages name

.github/workflows/update.yml
Unless we manually add the `feat` keyword to the PRs produced by the `update-versions.py` script, there won't be a new minor version.
=> Add the `feat` keyword to version-update PRs to make sure they produce a new minor

.github/workflows/update.yml
Run the `update-versions.py` daily instead of weekly to deliver new versions faster.
Related to https://github.com/stackbuilders/nixpkgs-terraform/issues/67.
=> chore: Update versions daily

versions.json
This PR updates the versions.json file for version 1.8.2 and 1.8.3 of Terraform.
=> feat: Add support for Terraform versions `1.8.2` and `1.8.3`

.github/workflows/build.yml, flake.lock, flake.nix, lib/build-terraform.nix, lib/releases.nix, patches/provider-path-1_9.patch, versions.json
**Problem:**
Updating the "nixpkgs" inputs resulted in a huge number of packages being rebuilt.
**Solution:**
As this project is constrained by the resources available for GH operations, this PR replaces branch references in the "nixpkgs" inputs with fixed commits to give better control over which packages are rebuilt. While assigning inputs to specific commits is not ideal, this adjustment reduces the risk of unexpected rebuilds.
=> feat: Initial support for Terraform 1.9 versions

cli/devenv.lock, vendor-hash.nix, versions.json
- fix: Update inputs on vendor-hash
- feat: Add Terraform versions 1.9.3 and 1.9.4
=> feat: Add Terraform versions `1.9.3` and `1.9.4`

.github/workflows/update.yml, cli/devenv.lock, devenv.lock, flake.lock, flake.nix
Tested in [this run of the update workflow](https://github.com/stackbuilders/nixpkgs-terraform/actions/runs/10991787463/job/30514855334?pr=91) where the creation of the PR was disabled using this temp changes e7c42585ec64a6044f99882034ed4010be716cbc.
Changes:
- Bumped devenv for both the main project and the cli tool with `devenv update`.
- Changed the commit hash in the `nixpkgs-1_9` input to the latest one to get go 1.22.7 with `nix flake update nixpkgs-1_9`
=> Bump go 1.22.7

versions.json
Since the automated workflow is broken, I generated these manually with [seppeljordan/nix-prefetch-github](https://github.com/seppeljordan/nix-prefetch-github) and `$ nix-prefetch-github hashicorp terraform --rev v1.10.X`. Then built the packages locally to get a correct vendorHash. This should be a temporary solution to make the new versions available for those using `>1.10.0`.
Closes https://github.com/stackbuilders/nixpkgs-terraform/issues/101.
=> feat: Add missing 1.10.X versions

versions.json
Manually adding these versions while we work on a permanent solution for the update script.
I'm using nurl with `nurl --hash https://github.com/hashicorp/terraform v1.10.5` to get the hash and then `nix build .#"\"1.10.5"\" ` to get the vendorHash from the error message.
=> feat: Manually add 1.10.4 and 1.10.5

.github/workflows/update.yml, flake.nix, lib/build-for.nix, lib/default.nix, lib/packages.nix, vendor-hash.nix
The following PR refactors `vendhor-hash.nix` to prevent breaking changes caused by adding or modifying flake inputs.
=> chore: Make `vendor-hash` less sensitive to `inputs` changes

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/update.yml
Pins the `devenv` version to `1.4` across all workflows to avoid an incompatibility issue between `devenv-1.5` and the `nixpkgs-24.11` channel:
https://github.com/stackbuilders/nixpkgs-terraform/actions/runs/14575140576/job/40879567074
=> ci: Pins `devenv` version to avoid incompatibility issues between `devenv-1.5` and `nixpkgs-24.11`

versions.json
Manually adding 1.12 versions while working on fixing the broken release and update workflows.
Release: https://github.com/stackbuilders/nixpkgs-terraform/actions/runs/15167632311
Update: https://github.com/stackbuilders/nixpkgs-terraform/actions/runs/15167877530
Fixes #124
=> feat: Add Terraform 1.12 versions

flake.lock, flake.nix
This pull request updates the `flake.nix` file to use more descriptive and streamlined URLs for Nixpkgs channels, providing clarity on their purpose and scope.
Key changes in `flake.nix`:
* Updated the `nixpkgs-1_0.url` to use the `nixos-23.05-small` channel with a comment explaining its scope for building versions from 1.0 to 1.5.
* Updated the `nixpkgs-1_6.url` to use the `nixos-24.05-small` channel with a comment explaining its scope for building versions from 1.6 to 1.8.
* Updated the `nixpkgs.url` to use the `nixpkgs-unstable` channel with a comment explaining its scope for building versions from 1.9 onwards.
=> feat: Update flake inputs

.github/workflows/update.yml
After the recent addition of the `--templates-dir` flag to the update command, we are missing a small change in the CI workflow that makes use of this command. This will fix it and also enable the new flag to take effect.
=> ci: Add missing flag for template dirs to the update workflow

.github/workflows/build.yml, .github/workflows/update.yml, flake.lock
This pull request adds a notification step to the GitHub Actions workflow. Now, if the `update` job fails, a Slack message will be sent to alert the team.
Workflow improvements:
* Added a `notify` job to `.github/workflows/update.yml` that triggers on failure of the `update` job and sends a Slack message using the `slackapi/slack-github-action`.
Fixes: #125
=> ci: Send notifications when the `update` workflow fails

cli/cmd/update.go
This pull request makes improvements to the handling of the `CLI_GITHUB_TOKEN` environment variable in the `cli/cmd/update.go` file. The changes ensure that the application does not fail if the token is missing, and instead logs a warning and gracefully handles unauthenticated requests to the GitHub API.
Error handling and authentication improvements:
* Changed the behavior when `CLI_GITHUB_TOKEN` is missing: instead of returning an error, the code now logs a warning message and continues, which allows the CLI to run in environments where the token is not set, albeit with possible rate limiting.
* Updated the GitHub client initialization in `getRepoReleases` to only use the authentication token if it is present, allowing unauthenticated requests when the token is missing.
=> ci(cli): Make easier to call the `update` command locally without a GH token

.github/workflows/build.yml, devenv.nix
This pull request makes minor improvements to the build workflow and development environment configuration, focusing on streamlining CI logic and updating the pre-commit hook configuration.
**Build workflow improvements:**
* Updated the `skipPush` parameter in `.github/workflows/build.yml` to only skip pushing when the branch is not `main`, improving caching behavior in CI.
* Simplified the package build step in `.github/workflows/build.yml` by removing conditional logic for checking the presence of the Cachix token; now always runs `nix flake check`.
**Development environment configuration:**
* Changed the pre-commit hook configuration in `devenv.nix` to use `git-hooks` instead of `pre-commit` for enabling `nixpkgs-fmt`, aligning with updated tooling.
=> ci: Change build job to only push binaries at the end
